/**
 * Shared private-use glyphs (UI.md §0.1), drawn by the core RP font sheet `font/glyph_E1.png`
 * (16×16 grid, cell = low byte of the code point; generated by tools/gen-assets.mjs, module core). PURE.
 *
 *   U+E100          chip
 *   U+E110–U+E143   cards: E110 + suit × 13 + rank, suits S H D C, ranks 2 … 10 J Q K A
 *   U+E144          card back
 *   U+E150–U+E153   suits S H D C
 *   U+E160–U+E165   dice faces 1–6
 *   U+E170 / E171   streak flame (lucky) / rain cloud (unlucky)
 *   U+E180–U+E185   VIP badges Bronze … Netherite
 *
 * (Card order inside E110–E143 is fixed here; Java uses the same code points.)
 * Glyphs are never put in lang strings: code prepends them as separate text components.
 */
import { type Card, RANKS, SUITS } from './cards';
import type { Raw } from './rawtext';

const g = (cp: number): string => String.fromCodePoint(cp);

export const CHIP_GLYPH = g(0xe100);
export const CARD_BACK_GLYPH = g(0xe144);
export const STREAK_FLAME_GLYPH = g(0xe170);
export const STREAK_CLOUD_GLYPH = g(0xe171);

export const cardCodePoint = (c: Card): number => 0xe110 + SUITS.indexOf(c.suit) * 13 + RANKS.indexOf(c.rank);
export const cardGlyph = (c: Card): string => g(cardCodePoint(c));
export const suitGlyph = (s: Card['suit']): string => g(0xe150 + SUITS.indexOf(s));
/** Die face 1–6 (out of range values are clamped). */
export const dieGlyph = (n: number): string => g(0xe160 + Math.max(0, Math.min(5, Math.floor(n) - 1)));
/** VIP badge 0 (Bronze) … 5 (Netherite). */
export const vipBadgeGlyph = (tier: number): string => g(0xe180 + Math.max(0, Math.min(5, Math.floor(tier))));

/** A glyph as a rawtext component, white (so the sheet's own colors show) and reset after. */
export const glyphRaw = (glyph: string): Raw => ({ text: '§f' + glyph + '§r' });
