#!/usr/bin/env node
// Generate src/core/logic/config-catalog.ts (every CONFIG.md key: type, default, range,
// section, owner, label keys) from docs/design/CONFIG.md + STRINGS.md.
//   node tools/gen-config.mjs           write the catalog
//   node tools/gen-config.mjs --check   exit 1 if the committed catalog is stale
/* global process, console */
/* eslint-disable no-console */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseConfigMd } from './lib/config-md.mjs';
import { parseStrings } from './lib/strings.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = path.resolve(ROOT, '../docs/design');
const OUT = path.join(ROOT, 'src/core/logic/config-catalog.ts');

const labels = new Set(parseStrings(fs.readFileSync(path.join(DOCS, 'STRINGS.md'), 'utf8')).entries.map((e) => e.key));
const { defs, errors, warnings } = parseConfigMd(fs.readFileSync(path.join(DOCS, 'CONFIG.md'), 'utf8'), labels);
if (errors.length) {
  for (const e of errors) console.error('  - ' + e);
  process.exit(1);
}
for (const w of warnings) console.warn('  warning: ' + w);

const body = defs.map((d) => '  ' + JSON.stringify(d).replace(/"([A-Za-z_]+)":/g, '$1:').replace(/"/g, "'") + ',').join('\n');
const text = `/**
 * GENERATED by tools/gen-config.mjs from docs/design/CONFIG.md - do not edit by hand.
 * Every tunable key of the game with type, default, range, admin-form section, owning module
 * and label keys (STRINGS.md §config). Read values through ctx.config (core/config.ts).
 */
import type { ConfigDef } from './config-schema';

export const CONFIG_CATALOG: readonly ConfigDef[] = [
${body}
];
`;
if (process.argv.includes('--check')) {
  const old = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (old !== text) {
    console.error('config-catalog.ts is stale; run: node tools/gen-config.mjs');
    process.exit(1);
  }
  console.log(`config catalog OK (${defs.length} keys)`);
} else {
  fs.writeFileSync(OUT, text);
  console.log(`wrote ${path.relative(ROOT, OUT)} (${defs.length} keys, ${warnings.length} warnings)`);
}
