package dev.nezo.burmaldaholic.games.slots.client;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.mojang.math.Axis;
import dev.nezo.burmaldaholic.Burmaldaholic;
import dev.nezo.burmaldaholic.client.fx.FxSettings;
import dev.nezo.burmaldaholic.client.render.SpectatorBlockEntityRenderer;
import dev.nezo.burmaldaholic.client.render.SpectatorRenderState;
import dev.nezo.burmaldaholic.core.anim.Beat;
import dev.nezo.burmaldaholic.core.anim.Timeline;
import dev.nezo.burmaldaholic.core.anim.TimelineSeed;
import dev.nezo.burmaldaholic.core.anim.WinTier;
import dev.nezo.burmaldaholic.core.sound.CasinoSounds;
import dev.nezo.burmaldaholic.core.table.CasinoTableBlock;
import dev.nezo.burmaldaholic.core.table.CasinoTableMenu;
import dev.nezo.burmaldaholic.core.table.TableType;
import dev.nezo.burmaldaholic.core.text.Texts;
import dev.nezo.burmaldaholic.games.slots.SlotMachineBlockEntity;
import dev.nezo.burmaldaholic.games.slots.SlotsModule;
import dev.nezo.burmaldaholic.games.slots.cabinet.CabinetBeats;
import dev.nezo.burmaldaholic.games.slots.cabinet.CabinetFrame;
import dev.nezo.burmaldaholic.games.slots.cabinet.CabinetFrames;
import dev.nezo.burmaldaholic.games.slots.cabinet.CabinetSync;
import dev.nezo.burmaldaholic.games.slots.cabinet.Marquee;
import dev.nezo.burmaldaholic.games.slots.v2.logic.Machine;
import dev.nezo.burmaldaholic.games.slots.v2.logic.SlotTiers;
import dev.nezo.burmaldaholic.games.slots.v2.logic.SlotTimeline;
import java.util.Map;
import java.util.WeakHashMap;
import net.fabricmc.fabric.api.client.rendering.v1.BlockEntityRendererRegistry;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.client.renderer.SubmitNodeCollector;
import net.minecraft.client.renderer.blockentity.BlockEntityRendererProvider;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.client.renderer.state.level.CameraRenderState;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.core.Direction;
import net.minecraft.locale.Language;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.util.FormattedCharSequence;
import net.minecraft.world.level.block.state.BlockState;
import org.jspecify.annotations.Nullable;

/**
 * In-world slot cabinet for spectators (slots.md §5.1–§5.2, JS14): the upper cabinet above the machine block with
 * five curved reel drums behind glass, a marquee with bulb patterns, and every feature of the spin — landing
 * squash, anticipation glow, win frames, Nether tumbles with {@code ×N}, End expanding sticky eggs, the Piglin's
 * Hoard grid, the Treasure Hunt board, the Dragon Wheel on top of the End cabinet and the floating tier word +
 * amount after the reveal gate.
 *
 * <p>Fidelity F10: everything comes from the block entity's {@link CabinetSync} sampled by the PURE
 * {@link CabinetFrames} at the SHARED clock ({@code (gameTime + partialTick) × 50 − startTick × 50}), so every
 * viewer and the player's screen land on the same tick. Nothing is drawn before the first v2 sync (v1 machines keep
 * their look). Late joiners (≥ 85 % of the shared part) get the settled frame. {@code anim.reduceMotion} → the
 * reduced frame; far away (≥ 24 blocks) → the settled LOD; {@code anim.flashes} off → no blinking.
 *
 * <p>Art (generated by lane B-L10, {@code bedrock/tools/assets/modules/slots.mjs}): symbol sheet
 * {@code textures/gui/slots/<m>_symbols_32.png} (16 × 11 cells of 32 px: col 0 base, col 1 blur; row = SLOTS.md §2
 * order), {@code textures/entity/slots/<m>_cabinet.png} (CAB_UV), {@code <m>_overlay.png} (OVL_UV: win frame, burn
 * pop, coin, empty cell, sticky column, glass), {@code <m>_marquee[_fs|_jackpot].png} (8 frames of 64 × 16) and
 * {@code end_wheel.png} (outer / middle / core discs + pointer).
 */
public final class SlotCabinetRenderer extends SpectatorBlockEntityRenderer<SlotMachineBlockEntity, SlotCabinetRenderer.State> {
	/** Full animation radius ({@code slots.inWorld.radius}, slots.md §2.6). */
	public static final int RADIUS = 24;
	private static final int FULL_BRIGHT = 0xF000F0;
	private static final double AUDIO_RANGE_SQ = 16 * 16;
	/** Reel-stop pitch ladder (slots.md §4.2). */
	private static final float[] STOP_PITCH = {1.0f, 1.12f, 1.26f, 1.5f, 1.68f};

	// ---- geometry: model pixels of the generated cabinet texture (1 texel = 1/16 block, CAB_UV of lane B-L10) ----
	// Local frame: front at +z, viewer's left at -x, the machine block's bottom at y = 0; the cabinet sits on top.
	private static final float PX = 1f / 16f;
	private static final float BODY_X = 7 * PX;
	private static final float BODY_Z0 = -6 * PX;
	private static final float BODY_Z1 = 6 * PX;
	private static final float BODY_Y0 = 1.0f;
	private static final float BODY_Y1 = BODY_Y0 + 13 * PX;
	private static final float WIN_X0 = -6 * PX;
	private static final float WIN_X1 = 6 * PX;
	private static final float WIN_Y1 = BODY_Y1 - 1 * PX;
	private static final float WIN_Y0 = BODY_Y1 - 10 * PX;
	/** Row height (3 rows in 9 px). */
	private static final float CELL_H = (WIN_Y1 - WIN_Y0) / 3f;
	private static final float FACE_Z = BODY_Z1;
	private static final float DRUM_R = 0.34f;
	private static final float MQ_X = 7.5f * PX;
	private static final float MQ_Z = 6.5f * PX;
	private static final float MQ_Y0 = BODY_Y1;
	private static final float MQ_Y1 = BODY_Y1 + 4 * PX;
	/** Wheel radius (outer ring) and centre height above the marquee. */
	private static final float WHEEL_R = 0.42f;

	private static final Identifier WHITE_TEX = Identifier.withDefaultNamespace("textures/block/snow.png");
	/** One pure-white texel of {@link #WHITE_TEX} (flat colour quads). */
	private static final float WU = 0.5f / 16f;
	private static final float WV = 1.5f / 16f;

	private static final Map<SlotMachineBlockEntity, ClientCabinet> CACHE = new WeakHashMap<>();

	private final Font font;

	public SlotCabinetRenderer(BlockEntityRendererProvider.Context ctx) {
		this.font = ctx.font();
	}

	/** Registers the renderer for the three machines (client module hook). */
	@SuppressWarnings("deprecation") // the only public 26.x registration path (vanilla BlockEntityRenderers.register is private)
	public static void register() {
		for (TableType<SlotMachineBlockEntity> type : SlotsModule.MACHINES.values()) {
			BlockEntityRendererRegistry.register(type.blockEntityType(), SlotCabinetRenderer::new);
		}
	}

	/** Per block entity client data: rebuilt only when the sync object changes (never per frame). */
	private static final class ClientCabinet {
		CabinetSync sync;
		Timeline beats;
		final CabinetFrame frame = new CabinetFrame();
		double firstSeen = Double.NaN;
		boolean catchUp;
		double lastT = Double.NaN;
		Object language;
		FormattedCharSequence tierWord;
		FormattedCharSequence tierAmount;
		int tierColor;
		int multFor = Integer.MIN_VALUE;
		FormattedCharSequence mult;
	}

	public static final class State extends SpectatorRenderState {
		boolean active;
		Machine machine = Machine.OVERWORLD;
		Direction facing = Direction.NORTH;
		@Nullable CabinetFrame frame;
		double t;
		boolean flashes;
		@Nullable FormattedCharSequence tierWord;
		@Nullable FormattedCharSequence tierAmount;
		int tierColor;
		@Nullable FormattedCharSequence mult;
	}

	@Override
	public State createRenderState() {
		return new State();
	}

	@Override
	protected int animateRadius() {
		return RADIUS;
	}

	@Override
	public boolean shouldRenderOffScreen() {
		return true; // the cabinet is taller than its block (upper part + wheel)
	}

	@Override
	protected void extractAnimated(SlotMachineBlockEntity be, State state, float partialTick) {
		CabinetSync sync = be.cabinetSync();
		state.active = sync != null && state.lod != Lod.STATIC;
		if (!state.active) return;
		ClientCabinet c = CACHE.computeIfAbsent(be, k -> new ClientCabinet());
		if (c.sync != sync) {
			boolean sameSpin = c.sync != null && c.sync.seq() == sync.seq() && c.sync.startTick() == sync.startTick();
			c.sync = sync;
			c.beats = CabinetBeats.timeline(sync);
			c.language = null;
			c.multFor = Integer.MIN_VALUE;
			if (!sameSpin) { // a republished step of the same spin (hunt pick, free spin) keeps the running clock state
				c.firstSeen = Double.NaN;
				c.lastT = Double.NaN;
			}
		}
		double t = state.levelMs - sync.startTick() * 50.0;
		if (Double.isNaN(c.firstSeen)) {
			c.firstSeen = t;
			c.catchUp = t > 0 && TimelineSeed.showSettled(t, sync.gateMs());
		}
		CabinetFrames.Motion motion = c.catchUp || state.lod != Lod.FULL ? CabinetFrames.Motion.SETTLED
			: FxSettings.reduceMotion() ? CabinetFrames.Motion.REDUCED : CabinetFrames.Motion.FULL;
		CabinetFrames.sample(sync, t, motion, c.frame);
		if (!c.catchUp && state.lod == Lod.FULL && state.distSq <= AUDIO_RANGE_SQ && !viewingOwnScreen(be)) cues(be, c, t);
		c.lastT = t;
		texts(c);
		BlockState bs = be.getBlockState();
		state.machine = sync.machine();
		state.facing = bs.hasProperty(CasinoTableBlock.FACING) ? bs.getValue(CasinoTableBlock.FACING) : Direction.NORTH;
		state.frame = c.frame;
		state.t = t;
		state.flashes = FxSettings.flashes();
		state.tierWord = c.tierWord;
		state.tierAmount = c.tierAmount;
		state.tierColor = c.tierColor;
		state.mult = c.frame.multAlpha > 0 ? multText(c, c.frame.multValue) : null;
	}

	/** The acting player hears the screen's sounds, not the cabinet's. */
	private static boolean viewingOwnScreen(SlotMachineBlockEntity be) {
		Minecraft mc = Minecraft.getInstance();
		return mc.gui.screen() instanceof AbstractContainerScreen<?> s && s.getMenu() instanceof CasinoTableMenu m && m.pos().equals(be.getBlockPos());
	}

	// ---- positional cues (spectators; volume × anim.volume) -------------------------------------------

	private static void cues(SlotMachineBlockEntity be, ClientCabinet c, double t) {
		if (Double.isNaN(c.lastT) || t <= c.lastT || t - c.lastT > 500) return;
		Minecraft mc = Minecraft.getInstance();
		if (mc.level == null) return;
		float vol = FxSettings.volume();
		if (vol <= 0) return;
		double x = be.getBlockPos().getX() + 0.5;
		double y = be.getBlockPos().getY() + 1.45;
		double z = be.getBlockPos().getZ() + 0.5;
		for (Beat b : c.beats.beats()) {
			double at = b.end();
			if (b.kind().equals(SlotTimeline.REEL_LAND)) {
				if (at > c.lastT && at <= t) {
					float pitch = STOP_PITCH[Math.max(0, Math.min(4, b.lane()))];
					play(mc, x, y, z, "slots.reel_stop", SoundEvents.WOODEN_BUTTON_CLICK_ON, 0.35f * vol, pitch);
				}
			} else if (b.at() > c.lastT && b.at() <= t) {
				switch (b.kind()) {
					case SlotTimeline.TUMBLE_EXPLODE -> play(mc, x, y, z, "slots.tumble", SoundEvents.FIRECHARGE_USE, 0.3f * vol, 1.2f);
					case SlotTimeline.MULT_UP -> play(mc, x, y, z, "slots.mult_up", SoundEvents.AMETHYST_BLOCK_CHIME, 0.4f * vol,
						Math.min(1.5f, 0.9f + 0.1f * b.arg(0)));
					case SlotTimeline.WILD_EXPAND -> play(mc, x, y, z, "slots.wild_expand", SoundEvents.ENDER_EYE_DEATH, 0.4f * vol, 1.2f);
					case SlotTimeline.WILD_STICK -> play(mc, x, y, z, "slots.wild_stick", SoundEvents.CHAIN_PLACE, 0.5f * vol, 1f);
					case SlotTimeline.WHEEL_UP -> play(mc, x, y + 0.6, z, "slots.wheel_up", SoundEvents.BEACON_ACTIVATE, 0.35f * vol, 0.8f);
					case SlotTimeline.HOARD_RESPIN -> play(mc, x, y, z, "slots.coin_land", SoundEvents.VAULT_EJECT_ITEM, 0.3f * vol, 1.3f);
					default -> {
					}
				}
			}
		}
	}

	private static void play(Minecraft mc, double x, double y, double z, String id, SoundEvent fallback, float vol, float pitch) {
		SoundEvent e = CasinoSounds.get(id);
		mc.level.playLocalSound(x, y, z, e != null ? e : fallback, SoundSource.BLOCKS, vol, pitch, false);
	}

	// ---- texts (cached per sync / language) ------------------------------------------------------------

	private static void texts(ClientCabinet c) {
		Object lang = Language.getInstance();
		if (c.language == lang) return;
		c.language = lang;
		c.multFor = Integer.MIN_VALUE;
		CabinetSync s = c.sync;
		Component word;
		if (s.maxWin()) {
			word = Component.translatable(SlotTiers.WORDS.maxWin());
			c.tierColor = 0xFFD8D8E0;
		} else if (s.jackpotTier() > 0) {
			word = Component.translatable(SlotTiers.WORDS.jackpot(), Component.translatable(jackpotTierKey(s.jackpotTier())));
			c.tierColor = jackpotColor(s.jackpotTier());
		} else {
			word = Component.translatable(SlotTiers.WORDS.key(s.tier()));
			c.tierColor = tierColor(s.tier());
		}
		c.tierWord = word.getVisualOrderText();
		c.tierAmount = Texts.chips(s.totalChips()).getVisualOrderText();
	}

	private static String jackpotTierKey(int tier) {
		return switch (tier) {
			case 1 -> "gui.burmaldaholic.slots.jackpot.tier.mini";
			case 2 -> "gui.burmaldaholic.slots.jackpot.tier.minor";
			case 3 -> "gui.burmaldaholic.slots.jackpot.tier.major";
			default -> "gui.burmaldaholic.slots.jackpot.tier.grand";
		};
	}

	/** Jackpot badge colours (slots.md §3.2). */
	static int jackpotColor(int tier) {
		return switch (tier) {
			case 1 -> 0xFF80FF40;
			case 2 -> 0xFF4080FF;
			case 3 -> 0xFFFFD640;
			default -> 0xFFFF40C0;
		};
	}

	private static FormattedCharSequence multText(ClientCabinet c, int value) {
		if (c.multFor != value) {
			c.multFor = value;
			c.mult = Component.translatable("gui.burmaldaholic.slots.tumble.mult", Texts.number(value)).getVisualOrderText();
		}
		return c.mult;
	}

	// ---- textures (generated, lane B-L10) ------------------------------------------------------------

	private static Identifier tex(String path) {
		return Burmaldaholic.id("textures/" + path + ".png");
	}

	private static final Identifier[] SHEET = new Identifier[3];
	private static final Identifier[] CABINET = new Identifier[3];
	private static final Identifier[] OVERLAY = new Identifier[3];
	private static final Identifier[][] MARQUEE = new Identifier[3][3];
	private static final Identifier WHEEL = tex("entity/slots/end_wheel");

	static {
		for (Machine m : Machine.values()) {
			int i = m.ordinal();
			SHEET[i] = tex("gui/slots/" + m.id + "_symbols_32");
			CABINET[i] = tex("entity/slots/" + m.id + "_cabinet");
			OVERLAY[i] = tex("entity/slots/" + m.id + "_overlay");
			for (Marquee.Variant v : Marquee.Variant.values()) MARQUEE[i][v.ordinal()] = tex("entity/slots/" + m.id + "_marquee" + v.suffix);
		}
	}

	/** Texel → UV on a 64 × 64 texture. */
	private static float t64(float texel) {
		return texel / 64f;
	}

	/** OVL_UV cells (texels on the 64 × 64 overlay). */
	private static final int[] OVL_WIN = {0, 0, 16, 16};
	private static final int[] OVL_POP = {16, 0, 16, 16};
	private static final int[] OVL_COIN = {32, 0, 16, 16};
	private static final int[] OVL_EMPTY = {48, 0, 16, 16};
	private static final int[] OVL_STICKY = {0, 16, 16, 48};
	private static final int[] OVL_GLASS = {16, 16, 32, 20};

	private static int drumColor(Machine m) {
		return switch (m) {
			case OVERWORLD -> 0xFFEFE6D2;
			case NETHER -> 0xFF2A1A16;
			case END -> 0xFF1C1426;
		};
	}

	private static int glowColor(Machine m) {
		return switch (m) {
			case OVERWORLD -> 0xFFFFD640;
			case NETHER -> 0xFFFF7A1A;
			case END -> 0xFFB040FF;
		};
	}

	// ---- submit ---------------------------------------------------------------------------------------

	@Override
	public void submit(State s, PoseStack pose, SubmitNodeCollector out, CameraRenderState camera) {
		if (!s.active || s.frame == null) return;
		CabinetFrame f = s.frame;
		int mi = s.machine.ordinal();
		int light = s.lightCoords;
		pose.pushPose();
		pose.translate(0.5f, 0f, 0.5f);
		pose.rotateAround(Axis.YP.rotationDegrees(-s.facing.toYRot()), 0f, 0f, 0f); // mulPose(Quaternionfc) is gone in 26.3

		out.submitCustomGeometry(pose, RenderTypes.entityCutout(CABINET[mi]), (p, vc) -> body(p, vc, light));
		out.submitCustomGeometry(pose, RenderTypes.entityCutout(WHITE_TEX), (p, vc) -> drums(p, vc, s, light));
		out.submitCustomGeometry(pose, RenderTypes.entityTranslucent(SHEET[mi]), (p, vc) -> cells(p, vc, s));
		out.submitCustomGeometry(pose, RenderTypes.entityTranslucentEmissive(OVERLAY[mi]), (p, vc) -> overlays(p, vc, s));
		out.submitCustomGeometry(pose, RenderTypes.entityTranslucentEmissive(WHITE_TEX), (p, vc) -> glow(p, vc, s));
		out.submitCustomGeometry(pose, RenderTypes.entityTranslucent(OVERLAY[mi]), (p, vc) -> glass(p, vc));
		double clock = f.marquee == Marquee.Pattern.IDLE ? s.levelMs : s.t;
		int mqFrame = Marquee.frame(f.marquee, clock, s.flashes);
		out.submitCustomGeometry(pose, RenderTypes.entityTranslucentEmissive(MARQUEE[mi][Marquee.variant(f.marquee).ordinal()]),
			(p, vc) -> marqueeFace(p, vc, mqFrame));
		if (f.wheelRise > 0 && s.machine == Machine.END) out.submitCustomGeometry(pose, RenderTypes.entityCutout(WHEEL), (p, vc) -> wheel(p, vc, s));
		pose.popPose();

		texts(s, pose, out, camera);
	}

	// ---- geometry helpers ----------------------------------------------------------------------------

	private static void vertex(PoseStack.Pose p, VertexConsumer vc, float x, float y, float z, float u, float v, int argb, int light, float nx,
			float ny, float nz) {
		vc.addVertex(p, x, y, z).setColor(argb).setUv(u, v).setOverlay(OverlayTexture.NO_OVERLAY).setLight(light).setNormal(p, nx, ny, nz);
	}

	/** Axis-aligned quad facing +z at depth {@code z}; (u0, v0) = top-left. */
	private static void front(PoseStack.Pose p, VertexConsumer vc, float x0, float y0, float x1, float y1, float z, float u0, float v0,
			float u1, float v1, int argb, int light) {
		vertex(p, vc, x0, y0, z, u0, v1, argb, light, 0, 0, 1);
		vertex(p, vc, x1, y0, z, u1, v1, argb, light, 0, 0, 1);
		vertex(p, vc, x1, y1, z, u1, v0, argb, light, 0, 0, 1);
		vertex(p, vc, x0, y1, z, u0, v0, argb, light, 0, 0, 1);
	}

	/** Front quad textured with an overlay cell ({@code [x, y, w, h]} texels on 64 × 64), full bright. */
	private static void front(PoseStack.Pose p, VertexConsumer vc, float x0, float y0, float x1, float y1, float z, int[] cell, int argb) {
		front(p, vc, x0, y0, x1, y1, z, t64(cell[0]), t64(cell[1]), t64(cell[0] + cell[2]), t64(cell[1] + cell[3]), argb, FULL_BRIGHT);
	}

	private static void flat(PoseStack.Pose p, VertexConsumer vc, float x0, float y0, float x1, float y1, float z, int argb, int light) {
		front(p, vc, x0, y0, x1, y1, z, WU, WV, WU, WV, argb, light);
	}

	private static void frame(PoseStack.Pose p, VertexConsumer vc, float x0, float y0, float x1, float y1, float z, float w, int argb, int light) {
		flat(p, vc, x0 - w, y1, x1 + w, y1 + w, z, argb, light);
		flat(p, vc, x0 - w, y0 - w, x1 + w, y0, z, argb, light);
		flat(p, vc, x0 - w, y0, x0, y1, z, argb, light);
		flat(p, vc, x1, y0, x1 + w, y1, z, argb, light);
	}

	/** Box face with a CAB_UV region (texels); corners a…d counter-clockwise seen from outside, a = bottom-left. */
	private static void face(PoseStack.Pose p, VertexConsumer vc, float ax, float ay, float az, float bx, float by, float bz, float cx, float cy,
			float cz, float dx, float dy, float dz, float[] uv, int argb, int light, float nx, float ny, float nz) {
		float u0 = t64(uv[0]);
		float v0 = t64(uv[1]);
		float u1 = t64(uv[0] + uv[2]);
		float v1 = t64(uv[1] + uv[3]);
		vertex(p, vc, ax, ay, az, u0, v1, argb, light, nx, ny, nz);
		vertex(p, vc, bx, by, bz, u1, v1, argb, light, nx, ny, nz);
		vertex(p, vc, cx, cy, cz, u1, v0, argb, light, nx, ny, nz);
		vertex(p, vc, dx, dy, dz, u0, v0, argb, light, nx, ny, nz);
	}

	/** Box with CAB_UV regions for front / back / sides / top (no bottom). */
	private static void box(PoseStack.Pose p, VertexConsumer vc, float x0, float y0, float z0, float x1, float y1, float z1, float[] frontUv,
			float[] backUv, float[] sideUv, float[] topUv, boolean withFront, int light) {
		if (withFront) face(p, vc, x0, y0, z1, x1, y0, z1, x1, y1, z1, x0, y1, z1, frontUv, 0xFFFFFFFF, light, 0, 0, 1);
		face(p, vc, x1, y0, z0, x0, y0, z0, x0, y1, z0, x1, y1, z0, backUv, 0xFFB8B8B8, light, 0, 0, -1);
		face(p, vc, x0, y0, z0, x0, y0, z1, x0, y1, z1, x0, y1, z0, sideUv, 0xFFD8D8D8, light, -1, 0, 0);
		face(p, vc, x1, y0, z1, x1, y0, z0, x1, y1, z0, x1, y1, z1, sideUv, 0xFFD8D8D8, light, 1, 0, 0);
		face(p, vc, x0, y1, z1, x1, y1, z1, x1, y1, z0, x0, y1, z0, topUv, 0xFFFFFFFF, light, 0, 1, 0);
	}

	private static int grey(float b, float a) {
		int c = Math.round(Math.max(0, Math.min(1, b)) * 255);
		int al = Math.round(Math.max(0, Math.min(1, a)) * 255);
		return al << 24 | c << 16 | c << 8 | c;
	}

	private static int withAlpha(int argb, float a) {
		int al = Math.round(Math.max(0, Math.min(1, a)) * 255);
		return al << 24 | argb & 0xFFFFFF;
	}

	private static int scaleRgb(int argb, float k) {
		int r = Math.min(255, Math.round((argb >> 16 & 0xFF) * k));
		int g = Math.min(255, Math.round((argb >> 8 & 0xFF) * k));
		int b = Math.min(255, Math.round((argb & 0xFF) * k));
		return argb & 0xFF000000 | r << 16 | g << 8 | b;
	}

	/** Window row (0 = top, 3 = bottom) → world y. */
	private static float rowY(float s) {
		return WIN_Y1 - s * CELL_H;
	}

	/** Drum surface depth at row {@code s} (curved cylinder behind the glass). */
	private static float drumZ(float s) {
		float dy = (s - 1.5f) * CELL_H;
		return FACE_Z - 0.03f - (DRUM_R - (float) Math.sqrt(DRUM_R * DRUM_R - dy * dy));
	}

	/** Drum shading: darker towards the top and bottom edges. */
	private static float shade(float s) {
		float d = (s - 1.5f) / 1.5f;
		return 1f - 0.38f * d * d;
	}

	private static float reelX0(int r) {
		return WIN_X0 + r * (WIN_X1 - WIN_X0) / 5f;
	}

	private static float reelX1(int r) {
		return WIN_X0 + (r + 1) * (WIN_X1 - WIN_X0) / 5f;
	}

	// ---- cabinet body (CAB_UV of the generated 64 × 64 cabinet texture) ---------------------------------------

	private static final float[] CAB_BACK = {14, 0, 14, 13};
	private static final float[] CAB_SIDE = {28, 0, 12, 13};
	private static final float[] CAB_TOP = {40, 0, 14, 12};
	private static final float[] MQ_FRONT = {0, 14, 15, 4};
	private static final float[] MQ_BACK = {15, 14, 15, 4};
	private static final float[] MQ_SIDE = {30, 14, 13, 4};
	private static final float[] MQ_TOP = {0, 19, 15, 13};

	private static void body(PoseStack.Pose p, VertexConsumer vc, int light) {
		box(p, vc, -BODY_X, BODY_Y0, BODY_Z0, BODY_X, BODY_Y1, BODY_Z1, null, CAB_BACK, CAB_SIDE, CAB_TOP, false, light);
		// front around the reel window: texel rows 0–1 (top), 10–13 (payout tray + plaque), columns 0–1 and 13–14
		frontCab(p, vc, -7, 0, 7, 1, light);
		frontCab(p, vc, -7, 10, 7, 13, light);
		frontCab(p, vc, -7, 1, -6, 10, light);
		frontCab(p, vc, 6, 1, 7, 10, light);
		box(p, vc, -MQ_X, MQ_Y0, -MQ_Z, MQ_X, MQ_Y1, MQ_Z, MQ_FRONT, MQ_BACK, MQ_SIDE, MQ_TOP, true, light);
	}

	/** Part of the cabinet front: model px x0..x1 (from the centre), texel rows r0..r1 from the top. */
	private static void frontCab(PoseStack.Pose p, VertexConsumer vc, int x0, int r0, int x1, int r1, int light) {
		front(p, vc, x0 * PX, BODY_Y1 - r1 * PX, x1 * PX, BODY_Y1 - r0 * PX, BODY_Z1, t64(x0 + 7), t64(r0), t64(x1 + 7), t64(r1), 0xFFFFFFFF,
			light);
	}

	// ---- drums (flat colours) -----------------------------------------------------------------------------

	private static void drums(PoseStack.Pose p, VertexConsumer vc, State s, int light) {
		CabinetFrame f = s.frame;
		flat(p, vc, WIN_X0, WIN_Y0, WIN_X1, WIN_Y1, FACE_Z - 0.2f, 0xFF050505, FULL_BRIGHT);
		int drum = drumColor(s.machine);
		for (int r = 0; r < 5; r++) {
			float bright = f.anticipate[r] > 0 ? 0.7f : 1f;
			float x0 = reelX0(r) + 0.004f;
			float x1 = reelX1(r) - 0.004f;
			for (int k = 0; k < 6; k++) {
				float s0 = k * 0.5f;
				float s1 = s0 + 0.5f;
				int c0 = scaleRgb(drum, shade(s0) * bright);
				int c1 = scaleRgb(drum, shade(s1) * bright);
				vertex(p, vc, x0, rowY(s1), drumZ(s1) - 0.004f, WU, WV, c1, FULL_BRIGHT, 0, 0, 1);
				vertex(p, vc, x1, rowY(s1), drumZ(s1) - 0.004f, WU, WV, c1, FULL_BRIGHT, 0, 0, 1);
				vertex(p, vc, x1, rowY(s0), drumZ(s0) - 0.004f, WU, WV, c0, FULL_BRIGHT, 0, 0, 1);
				vertex(p, vc, x0, rowY(s0), drumZ(s0) - 0.004f, WU, WV, c0, FULL_BRIGHT, 0, 0, 1);
			}
		}
		for (int r = 1; r < 5; r++) {
			float x = reelX0(r);
			flat(p, vc, x - 0.004f, WIN_Y0, x + 0.004f, WIN_Y1, FACE_Z - 0.006f, 0xFF1A1410, light);
		}
		if (f.hunt) {
			for (int c = 0; c < CabinetSync.CELLS; c++) {
				flat(p, vc, reelX0(c / 3) + 0.005f, rowY(c % 3 + 1) + 0.005f, reelX1(c / 3) - 0.005f, rowY(c % 3) - 0.005f, FACE_Z - 0.012f,
					f.chest[c] == CabinetFrame.CHEST_CLOSED ? 0xFF3A2A18 : 0xFF241A10, FULL_BRIGHT);
			}
		}
	}

	// ---- symbol cells (sheet: col 0 base, col 1 blur, row = symbol) -------------------------------------------

	private static final float SU = 32f / 512f;
	private static final float SV = 32f / 352f;

	private static void cells(PoseStack.Pose p, VertexConsumer vc, State s) {
		CabinetFrame f = s.frame;
		boolean board = f.hoard && f.hoardFade >= 1f || f.hunt;
		for (int r = 0; r < CabinetFrame.REELS; r++) {
			if (board || f.eggGrow[r] >= 1f) continue;
			for (int i = 0; i < f.count[r]; i++) {
				float a = f.alpha[r][i] * (f.hoard ? 1f - f.hoardFade : 1f);
				if (a <= 0.01f) continue;
				cell(p, vc, r, f.y[r][i], f.sym[r][i], f.blur[r][i], f.scale[r][i], f.squash[r], f.bright[r][i], a);
			}
		}
		if (f.hunt) {
			for (int c = 0; c < CabinetSync.CELLS; c++) {
				boolean closed = f.chest[c] == CabinetFrame.CHEST_CLOSED;
				cell(p, vc, c / 3, c % 3, 2, false, closed ? 1f : 0.8f, 1f, closed ? 1f : 0.45f, 1f);
			}
		}
	}

	/** One square symbol on the drum, clipped to the window, curved (2 strips) and shaded. */
	private static void cell(PoseStack.Pose p, VertexConsumer vc, int r, float row, int sym, boolean blur, float scale, float squash, float bright,
			float alpha) {
		float ua = blur ? SU : 0f;
		float va = Math.floorMod(sym, 11) * SV;
		float size = Math.min(reelX1(r) - reelX0(r), CELL_H) * 0.9f * scale;
		float hw = size / 2f;
		float halfY = hw / CELL_H * squash;
		float cx = (reelX0(r) + reelX1(r)) / 2f;
		float sc = row + 0.5f;
		float s0 = sc - halfY;
		float s1 = sc + halfY;
		float cs0 = Math.max(0f, s0);
		float cs1 = Math.min(3f, s1);
		if (cs1 <= cs0) return;
		float vTop = va + SV * (cs0 - s0) / (s1 - s0);
		float vBot = va + SV * (cs1 - s0) / (s1 - s0);
		float sm = (cs0 + cs1) / 2f;
		float vm = (vTop + vBot) / 2f;
		strip(p, vc, cx - hw, cx + hw, cs0, sm, ua, ua + SU, vTop, vm, bright, alpha);
		strip(p, vc, cx - hw, cx + hw, sm, cs1, ua, ua + SU, vm, vBot, bright, alpha);
	}

	/** Horizontal strip between rows {@code s0} (top) and {@code s1} on the drum surface. */
	private static void strip(PoseStack.Pose p, VertexConsumer vc, float x0, float x1, float s0, float s1, float u0, float u1, float v0, float v1,
			float bright, float alpha) {
		int c0 = grey(bright * shade(s0), alpha);
		int c1 = grey(bright * shade(s1), alpha);
		float z0 = drumZ(s0);
		float z1 = drumZ(s1);
		vertex(p, vc, x0, rowY(s1), z1, u0, v1, c1, FULL_BRIGHT, 0, 0, 1);
		vertex(p, vc, x1, rowY(s1), z1, u1, v1, c1, FULL_BRIGHT, 0, 0, 1);
		vertex(p, vc, x1, rowY(s0), z0, u1, v0, c0, FULL_BRIGHT, 0, 0, 1);
		vertex(p, vc, x0, rowY(s0), z0, u0, v0, c0, FULL_BRIGHT, 0, 0, 1);
	}

	// ---- overlay texture (emissive): win frames, burn, sticky eggs, hoard cells ------------------------------

	private static void overlays(PoseStack.Pose p, VertexConsumer vc, State s) {
		CabinetFrame f = s.frame;
		float z = FACE_Z - 0.014f;
		if (f.winMask != 0 && (f.winOn || !s.flashes)) {
			for (int c = 0; c < CabinetSync.CELLS; c++) {
				if ((f.winMask & 1 << c) == 0) continue;
				front(p, vc, reelX0(c / 3), rowY(c % 3 + 1), reelX1(c / 3), rowY(c % 3), z, OVL_WIN, 0xFFFFFFFF);
			}
		}
		boolean board = f.hunt || f.hoard && f.hoardFade >= 1f;
		for (int r = 0; r < CabinetFrame.REELS; r++) {
			for (int i = 0; i < f.count[r]; i++) {
				if (f.burn[r][i] <= 0) continue;
				float row = f.y[r][i];
				front(p, vc, reelX0(r), rowY(Math.min(3, row + 1)), reelX1(r), rowY(Math.max(0, row)), z - 0.002f, OVL_POP,
					withAlpha(0xFFFFFFFF, f.burn[r][i]));
			}
			if (f.eggGrow[r] > 0 && !board) {
				float g = (f.eggGrow[r] - 1f / 3f) / (2f / 3f);
				float top = f.eggRow[r] * (1 - g);
				float bot = f.eggRow[r] + 1 + (2 - f.eggRow[r]) * g;
				float cx = (reelX0(r) + reelX1(r)) / 2f;
				float hw = (reelX1(r) - reelX0(r)) / 2f - 0.004f;
				int n = 6;
				for (int k = 0; k < n; k++) {
					float a = top + (bot - top) * k / n;
					float b = top + (bot - top) * (k + 1) / n;
					float va = t64(OVL_STICKY[1] + OVL_STICKY[3] * k / (float) n);
					float vb = t64(OVL_STICKY[1] + OVL_STICKY[3] * (k + 1) / (float) n);
					strip(p, vc, cx - hw, cx + hw, a, b, t64(OVL_STICKY[0]), t64(OVL_STICKY[0] + OVL_STICKY[2]), va, vb, 1f, 1f);
				}
			}
		}
		if (f.hoard) {
			for (int c = 0; c < CabinetSync.CELLS; c++) {
				boolean coin = (f.coinMask & 1 << c) != 0;
				float pop = coin ? f.coinPop[c] : 1f;
				float cx = (reelX0(c / 3) + reelX1(c / 3)) / 2f;
				float cy = rowY(c % 3 + 0.5f);
				float hw = (reelX1(c / 3) - reelX0(c / 3)) / 2f * pop;
				float hh = CELL_H / 2f * pop;
				front(p, vc, cx - hw, cy - hh, cx + hw, cy + hh, FACE_Z - 0.012f, coin ? OVL_COIN : OVL_EMPTY, withAlpha(0xFFFFFFFF, f.hoardFade));
			}
		}
	}

	// ---- emissive flat FX -------------------------------------------------------------------------------

	private static void glow(PoseStack.Pose p, VertexConsumer vc, State s) {
		CabinetFrame f = s.frame;
		float z = FACE_Z - 0.016f;
		for (int r = 0; r < CabinetFrame.REELS; r++) {
			if (f.anticipate[r] > 0) {
				int col = withAlpha(glowColor(s.machine), 0.9f * (s.flashes ? f.anticipate[r] : 1f));
				frame(p, vc, reelX0(r) + 0.004f, WIN_Y0 + 0.004f, reelX1(r) - 0.004f, WIN_Y1 - 0.004f, z, 0.01f, col, FULL_BRIGHT);
			}
			if (f.chain[r] > 0) {
				float cs = f.chainScale[r];
				float cx = (reelX0(r) + reelX1(r)) / 2f;
				float hw = (reelX1(r) - reelX0(r)) / 2f * cs - 0.004f;
				float cy = rowY(1.5f);
				float hh = 1.5f * CELL_H * cs - 0.004f;
				frame(p, vc, cx - hw, cy - hh, cx + hw, cy + hh, z - 0.001f, 0.008f, withAlpha(0xFFC080FF, f.chain[r]), FULL_BRIGHT);
			}
		}
		if (f.hoard) {
			for (int c = 0; c < CabinetSync.CELLS; c++) {
				float x0 = reelX0(c / 3) + 0.006f;
				float x1 = reelX1(c / 3) - 0.006f;
				float yb = rowY(c % 3 + 1) + 0.006f;
				float yt = rowY(c % 3) - 0.006f;
				if (f.coinLit[c] > 0) flat(p, vc, x0, yb, x1, yt, z, withAlpha(0xFFFFC400, 0.45f * f.coinLit[c]), FULL_BRIGHT);
				if ((f.coinMask & 1 << c) != 0 && f.coinValue[c] < 0) frame(p, vc, x0, yb, x1, yt, z, 0.008f, jackpotColor(-f.coinValue[c]), FULL_BRIGHT);
				if (f.cellSpin[c] >= 0) {
					for (int k = 0; k < 2; k++) {
						float u = (f.cellSpin[c] + k * 0.5f) % 1f;
						float yy = yt - (yt - yb) * u;
						flat(p, vc, x0 + 0.015f, Math.max(yb, yy - 0.012f), x1 - 0.015f, Math.min(yt, yy + 0.012f), z, 0xC0FF7A1A, FULL_BRIGHT);
					}
				}
			}
			for (int i = 0; i < 3; i++) {
				float x = -0.06f + i * 0.06f;
				flat(p, vc, x - 0.014f, WIN_Y1 + 0.014f, x + 0.014f, WIN_Y1 + 0.028f, BODY_Z1 + 0.002f, i < f.pips ? 0xFFFFC400 : 0xFF3A1A10,
					FULL_BRIGHT);
			}
		}
		if (f.hunt) {
			for (int c = 0; c < CabinetSync.CELLS; c++) {
				int e = f.chest[c];
				if (e == CabinetFrame.CHEST_CLOSED) continue;
				int col = e > 0 ? 0xFFFFD640 : e < 0 ? jackpotColor(-e) : 0xFF40C040;
				int r = c / 3;
				int row = c % 3;
				frame(p, vc, reelX0(r) + 0.01f, rowY(row + 1) + 0.01f, reelX1(r) - 0.01f, rowY(row) - 0.01f, z, 0.008f, col, FULL_BRIGHT);
				float cx = (reelX0(r) + reelX1(r)) / 2f;
				float cy = rowY(row + 0.5f);
				flat(p, vc, cx - 0.025f, cy - 0.025f, cx + 0.025f, cy + 0.025f, z - 0.001f, withAlpha(col, 0.85f), FULL_BRIGHT);
			}
		}
	}

	private static void glass(PoseStack.Pose p, VertexConsumer vc) {
		front(p, vc, WIN_X0, WIN_Y0, WIN_X1, WIN_Y1, FACE_Z + 0.004f, OVL_GLASS, 0x70FFFFFF);
	}

	/** Marquee panel: frame {@code f} of the 8-frame strip on the marquee box front, glowing. */
	private static void marqueeFace(PoseStack.Pose p, VertexConsumer vc, int f) {
		float v0 = f / (float) Marquee.FRAMES;
		front(p, vc, -MQ_X, MQ_Y0, MQ_X, MQ_Y1, MQ_Z + 0.004f, 0f, v0, 1f, v0 + 1f / Marquee.FRAMES, 0xFFFFFFFF, FULL_BRIGHT);
	}

	// ---- Dragon Wheel (end_wheel.png: outer 64 px at (0,0), middle 48 at (64,0), core 32 at (64,48), pointer at (96,48)) ----

	private static final float[][] DISC_UV = {{0, 0, 64}, {64, 0, 48}, {64, 48, 32}};
	/** Disc radii so each ring's rim meets the hole of the ring outside it (generated rIn/rOut ratios ≈ 0.61). */
	private static final float[] DISC_R = {WHEEL_R, WHEEL_R * 0.61f, WHEEL_R * 0.61f * 0.61f};
	private static final float[] CORNER_X = {-1, 1, 1, -1};
	private static final float[] CORNER_Y = {-1, -1, 1, 1};
	private static final float[] CORNER_U = {0, 1, 1, 0};
	private static final float[] CORNER_V = {1, 1, 0, 0};

	private static void wheel(PoseStack.Pose p, VertexConsumer vc, State s) {
		CabinetFrame f = s.frame;
		float rise = Math.max(0f, f.wheelRise);
		float cy = MQ_Y1 + 0.06f + WHEEL_R * Math.min(1f, rise);
		for (int ring = 0; ring < 3; ring++) {
			// rings of this bonus that are not up yet idle at their seeded pre-spin angle (a parked 0° read as wedge 0);
			// rings the bonus never reaches stay at rest
			float angle = f.ringSize[ring] > 0 ? f.ringAngle[ring] : 0f;
			float br = ring < f.ringCount ? f.ringBright[ring] : 0.4f;
			disc(p, vc, cy, ring * 0.004f, DISC_R[ring] * rise, angle, DISC_UV[ring], grey(br, 1f));
		}
		float pr = 0.07f * rise;
		float py = cy + WHEEL_R * rise;
		front(p, vc, -pr, py - pr, pr, py + pr, 0.016f, 96f / 128f, 48f / 128f, 112f / 128f, 64f / 128f, 0xFFFFFFFF, FULL_BRIGHT);
	}

	/** A textured disc rotated clockwise (seen from the front) by {@code angleDeg}; wedge 0 starts at 12 o'clock. */
	private static void disc(PoseStack.Pose p, VertexConsumer vc, float cy, float z, float r, float angleDeg, float[] uv, int col) {
		double a = Math.toRadians(angleDeg);
		float cos = (float) Math.cos(a);
		float sin = (float) Math.sin(a);
		float u0 = uv[0] / 128f;
		float v0 = uv[1] / 128f;
		float du = uv[2] / 128f;
		for (int i = 0; i < 4; i++) {
			float dx = CORNER_X[i] * r;
			float dy = CORNER_Y[i] * r;
			float x = dx * cos + dy * sin;
			float y = -dx * sin + dy * cos;
			vertex(p, vc, x, cy + y, z, u0 + CORNER_U[i] * du, v0 + CORNER_V[i] * du, col, FULL_BRIGHT, 0, 0, 1);
		}
	}

	// ---- floating texts ---------------------------------------------------------------------------------

	private void texts(State s, PoseStack pose, SubmitNodeCollector out, CameraRenderState camera) {
		CabinetFrame f = s.frame;
		if (f.tierAlpha > 0.05f && s.tierWord != null) {
			pose.pushPose();
			pose.translate(0.5f, 2.35f + f.tierRise + (f.wheelRise > 0 ? 0.95f : 0f), 0.5f);
			pose.rotateAround(camera.orientation, 0f, 0f, 0f);
			pose.scale(0.024f, -0.024f, 0.024f);
			int outline = withAlpha(0xFF1A0E00, f.tierAlpha);
			out.submitText(pose, -font.width(s.tierWord) / 2f, 0, s.tierWord, false, Font.DisplayMode.NORMAL, FULL_BRIGHT,
				withAlpha(s.tierColor, f.tierAlpha), 0, outline);
			if (s.tierAmount != null) {
				pose.scale(0.7f, 0.7f, 0.7f);
				out.submitText(pose, -font.width(s.tierAmount) / 2f, 14, s.tierAmount, false, Font.DisplayMode.NORMAL, FULL_BRIGHT,
					withAlpha(0xFFFFFFFF, f.tierAlpha), 0, outline);
			}
			pose.popPose();
		}
		if (f.multAlpha > 0.05f && s.mult != null) {
			pose.pushPose();
			float d = FACE_Z + 0.06f;
			pose.translate(0.5f + s.facing.getStepX() * d, WIN_Y1 + 0.05f + 0.15f * f.multRise, 0.5f + s.facing.getStepZ() * d);
			pose.rotateAround(camera.orientation, 0f, 0f, 0f);
			pose.scale(0.012f, -0.012f, 0.012f);
			out.submitText(pose, -font.width(s.mult) / 2f, 0, s.mult, false, Font.DisplayMode.NORMAL, FULL_BRIGHT,
				withAlpha(0xFFFF7A1A, f.multAlpha), 0, withAlpha(0xFF200800, f.multAlpha));
			pose.popPose();
		}
	}

	/** Tier word colour: Big gold, Mega orange, Epic magenta (slots.md §4.12 ray colours). */
	static int tierColor(WinTier tier) {
		return switch (tier) {
			case EPIC -> 0xFFFF40C0;
			case MEGA -> 0xFFFF8A1A;
			default -> 0xFFFFD640;
		};
	}
}
