package dev.nezo.burmaldaholic.games.slots.client;

import dev.nezo.burmaldaholic.client.fx.CasinoParticle;
import dev.nezo.burmaldaholic.games.slots.SlotsFx;
import net.fabricmc.fabric.api.client.particle.v1.ParticleProviderRegistry;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.particle.Particle;
import net.minecraft.client.particle.ParticleProvider;
import net.minecraft.client.particle.SingleQuadParticle;
import net.minecraft.client.particle.SpriteSet;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraft.util.RandomSource;

/**
 * Client providers of the slots module particles (slots.md §9.3, JS15):
 * <ul>
 *   <li>{@code ember_burst} — 4-frame ember, orange → red, rises 1.5 b/s, flickers, 0.8 s (Nether tumble step);</li>
 *   <li>{@code void_motes} — purple mote, slow rise 0.4 b/s, 2 s (End sticky wild).</li>
 * </ul>
 * Both are full-bright, translucent and never collide, and share the casino live budget ({@link CasinoParticle#acquire},
 * ≤ 400 casino particles alive; docs/architecture/animation.md §2.3). Sprites: {@code particles/slots/*.json} →
 * {@code textures/particle/slots/{ember_burst,void_motes}_0..3.png} (generated by the slots art module, lane B-L10).
 */
public final class SlotsParticles {
	private SlotsParticles() {}

	public static void register() {
		SimpleParticleType ember = SlotsFx.emberBurst();
		SimpleParticleType motes = SlotsFx.voidMotes();
		if (ember != null) ParticleProviderRegistry.getInstance().register(ember, sprites -> new EmberProvider(sprites));
		if (motes != null) ParticleProviderRegistry.getInstance().register(motes, sprites -> new MoteProvider(sprites));
	}

	private static final int FULL_BRIGHT = 0xF000F0;

	/** Rising, flickering ember. */
	static final class Ember extends SingleQuadParticle {
		private final SpriteSet sprites;

		private int token;

		Ember(ClientLevel level, double x, double y, double z, double dx, double dz, SpriteSet sprites, RandomSource random, int token) {
			super(level, x, y, z, sprites.first());
			this.sprites = sprites;
			this.token = token;
			this.lifetime = 12 + random.nextInt(6);
			this.hasPhysics = false;
			this.gravity = 0;
			this.friction = 0.92f;
			this.xd = dx * 0.4;
			this.zd = dz * 0.4;
			this.yd = 0.075 + random.nextFloat() * 0.02;
			this.quadSize = 0.045f + random.nextFloat() * 0.03f;
			setSpriteFromAge(sprites);
		}

		@Override
		public void tick() {
			super.tick();
			if (removed) return;
			setSpriteFromAge(sprites);
			float u = age / (float) lifetime;
			setColor(1f, 1f - 0.35f * u, 1f - 0.5f * u); // the sprite is orange; cool it towards red as it dies
			setAlpha((1f - u * u) * (0.75f + 0.25f * random.nextFloat()));
		}

		@Override
		public void remove() {
			CasinoParticle.release(token);
			token = -1;
			super.remove();
		}

		@Override
		protected Layer getLayer() {
			return Layer.TRANSLUCENT;
		}

		@Override
		protected int getLightCoords(float partialTick) {
			return FULL_BRIGHT;
		}
	}

	/** Slow purple mote that fades in, drifts up and fades out. */
	static final class Mote extends SingleQuadParticle {
		private final SpriteSet sprites;

		private int token;

		Mote(ClientLevel level, double x, double y, double z, double dx, double dz, SpriteSet sprites, RandomSource random, int token) {
			super(level, x, y, z, sprites.first());
			this.sprites = sprites;
			this.token = token;
			this.lifetime = 34 + random.nextInt(12);
			this.hasPhysics = false;
			this.gravity = 0;
			this.friction = 0.98f;
			this.xd = dx * 0.2;
			this.zd = dz * 0.2;
			this.yd = 0.02;
			this.quadSize = 0.05f + random.nextFloat() * 0.03f;
			setAlpha(0f);
			setSpriteFromAge(sprites);
		}

		@Override
		public void tick() {
			super.tick();
			if (removed) return;
			setSpriteFromAge(sprites);
			float u = age / (float) lifetime;
			setAlpha(Math.min(1f, u * 5f) * (1f - u));
			this.xd += Math.sin((age + x * 7) * 0.3) * 0.0015;
		}

		@Override
		public void remove() {
			CasinoParticle.release(token);
			token = -1;
			super.remove();
		}

		@Override
		protected Layer getLayer() {
			return Layer.TRANSLUCENT;
		}

		@Override
		protected int getLightCoords(float partialTick) {
			return FULL_BRIGHT;
		}
	}

	record EmberProvider(SpriteSet sprites) implements ParticleProvider<SimpleParticleType> {
		@Override
		public Particle createParticle(SimpleParticleType type, ClientLevel level, double x, double y, double z, double dx, double dy, double dz,
				RandomSource random) {
			int token = CasinoParticle.acquire(level);
			return token < 0 ? null : new Ember(level, x, y, z, dx, dz, sprites, random, token);
		}
	}

	record MoteProvider(SpriteSet sprites) implements ParticleProvider<SimpleParticleType> {
		@Override
		public Particle createParticle(SimpleParticleType type, ClientLevel level, double x, double y, double z, double dx, double dy, double dz,
				RandomSource random) {
			int token = CasinoParticle.acquire(level);
			return token < 0 ? null : new Mote(level, x, y, z, dx, dz, sprites, random, token);
		}
	}
}
