// Architecture rules for parallel development:
//  1. modules.json == MODULE_IDS (src/core/logic/ids.ts) == src/modules.ts; folders exist.
//  2. Files under any `logic/` folder are PURE: no @minecraft/* imports, and relative
//     imports may only reach other `logic/` folders.
//  3. Module boundaries: a module may import core (core/index.ts or core/logic/**) and other
//     modules' `api.ts` only - never their internals.
//  4. packs/<id>/ contains only BP/ and RP/; no manifest.json (generated by the build).
import fs from 'node:fs';
import path from 'node:path';
import { MODULES, ROOT, fail, rel, walk } from './lib.mjs';

const errors = [];
const ids = MODULES.map((m) => m.id);

// 1. registry consistency
const idsTs = fs.readFileSync(path.join(ROOT, 'src/core/logic/ids.ts'), 'utf8');
const tsIds = [...(/MODULE_IDS = \[([\s\S]*?)\]/.exec(idsTs)?.[1] ?? '').matchAll(/'([a-z]+)'/g)].map((m) => m[1]);
if (tsIds.join() !== ids.join()) errors.push(`MODULE_IDS in ids.ts [${tsIds}] != modules.json [${ids}]`);
const modulesTs = fs.readFileSync(path.join(ROOT, 'src/modules.ts'), 'utf8');
for (const m of MODULES) {
  if (!fs.existsSync(path.join(ROOT, m.src, 'index.ts'))) errors.push(`${m.src}/index.ts missing`);
  if (!new RegExp(`\\b${m.id}Module\\b`).test(modulesTs)) errors.push(`src/modules.ts does not list ${m.id}Module`);
  if (!fs.existsSync(path.join(ROOT, 'lang', m.id))) errors.push(`lang/${m.id}/ missing`);
}

// module of a file = longest matching src prefix
const srcOf = MODULES.map((m) => ({ id: m.id, dir: path.join(ROOT, m.src) + path.sep })).sort((a, b) => b.dir.length - a.dir.length);
const moduleOf = (f) => srcOf.find((m) => f.startsWith(m.dir));
const isLogic = (f) => f.split(path.sep).includes('logic');

function resolveImport(from, spec) {
  const base = path.resolve(path.dirname(from), spec);
  for (const c of [base, `${base}.ts`, path.join(base, 'index.ts')]) if (fs.existsSync(c) && fs.statSync(c).isFile()) return c;
  return undefined;
}

for (const file of walk(path.join(ROOT, 'src')).filter((f) => f.endsWith('.ts'))) {
  const src = fs.readFileSync(file, 'utf8');
  const me = moduleOf(file);
  for (const m of src.matchAll(/(?:^|\n)\s*(?:import|export)[^'"]*?from\s*['"]([^'"]+)['"]|import\(\s*['"]([^'"]+)['"]\s*\)|(?:^|\n)\s*import\s*['"]([^'"]+)['"]/g)) {
    const spec = m[1] ?? m[2] ?? m[3];
    const typeOnly = /^\s*(import|export)\s+type\b/.test(m[0].trim());
    if (isLogic(file) && spec.startsWith('@minecraft/') && !file.endsWith('.test.ts')) {
      errors.push(`${rel(file)}: pure logic file imports ${spec}`);
    }
    if (!spec.startsWith('.')) continue;
    const target = resolveImport(file, spec);
    if (!target) {
      errors.push(`${rel(file)}: cannot resolve ${spec}`);
      continue;
    }
    if (isLogic(file) && !isLogic(target)) errors.push(`${rel(file)}: pure logic file imports non-logic ${rel(target)}`);
    const other = moduleOf(target);
    if (!me || !other || other.id === me.id) continue;
    const inner = path.relative(other.dir, target).split(path.sep).join('/');
    const allowed = other.id === 'core' ? inner === 'index.ts' || inner.startsWith('logic/') : inner === 'api.ts' || (typeOnly && inner === 'api.ts');
    if (!allowed) errors.push(`${rel(file)}: module '${me.id}' imports '${other.id}' internals (${rel(target)}); use ${other.id === 'core' ? 'core/index.ts' : `${other.id}/api.ts`}`);
  }
}

// 4. packs layout
const packsDir = path.join(ROOT, 'packs');
for (const d of fs.readdirSync(packsDir)) {
  if (!ids.includes(d)) {
    errors.push(`packs/${d}: not a module id`);
    continue;
  }
  for (const sub of fs.readdirSync(path.join(packsDir, d))) if (!['BP', 'RP'].includes(sub)) errors.push(`packs/${d}/${sub}: only BP/ and RP/ allowed`);
}
for (const f of walk(packsDir)) if (path.basename(f) === 'manifest.json') errors.push(`${rel(f)}: manifests are generated by the build`);

fail(errors, 'Architecture check failed');
console.log('arch OK');
