package dev.nezo.burmaldaholic.client.ui;

import dev.nezo.burmaldaholic.Burmaldaholic;
import net.minecraft.client.Minecraft;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.Level;

/**
 * The look of a casino screen by location (docs/design/visual/cards.md §7, tables.md §2.1, extras.md §2.3): the three
 * casino themes (village parlour, Piglin bastion, End high-roller lounge) plus the two meta scenes of the Casino Menu
 * (the art-deco lobby and the Loan Shark's night harbour). Each theme names its backdrop sheet (1 art px = 1 GUI px,
 * cropped at the centre, never scaled), its gold nine-slice frame and its title banner (generated by
 * {@code tools/assets/modules/ui.mjs}), and an accent colour for celebrations.
 *
 * <p>Location themes follow the dimension the player is in ({@link #current()}): overworld → village, nether →
 * bastion, end → end. Screens of a block entity that knows its casino may pass their own ({@link #byId}).
 */
public enum CasinoTheme {
	VILLAGE("village", "textures/gui/core/cards/backdrop_village.png", 428, 240, 0xFFFFD640),
	BASTION("bastion", "textures/gui/core/cards/backdrop_bastion.png", 428, 240, 0xFFFF6020),
	END("end", "textures/gui/core/cards/backdrop_end.png", 428, 240, 0xFFD696FF),
	LOBBY("lobby", "textures/gui/core/menu/lobby_backdrop.png", 400, 240, 0xFFFFD640),
	LOAN("loan", "textures/gui/core/menu/loan_backdrop.png", 400, 240, 0xFFD83440);

	public final String id;
	/** Backdrop sheet (UV-blitted) and its size. */
	public final Identifier backdrop;
	public final int backdropW;
	public final int backdropH;
	/** Celebration / highlight accent (ARGB). */
	public final int accent;
	/** Gold nine-slice frame (64², border 12, transparent centre): {@code burmaldaholic:core/ui/frame_<id>}. */
	public final Identifier frame;
	/** Title banner nine-slice (48 × 24, border 10): {@code burmaldaholic:core/ui/banner_<id>}. */
	public final Identifier banner;

	CasinoTheme(String id, String backdrop, int w, int h, int accent) {
		this.id = id;
		this.backdrop = Burmaldaholic.id(backdrop);
		this.backdropW = w;
		this.backdropH = h;
		this.accent = accent;
		this.frame = UiSprites.sprite("ui/frame_" + id);
		this.banner = UiSprites.sprite("ui/banner_" + id);
	}

	/** Frame border in GUI px (all theme frames). */
	public static final int FRAME_BORDER = 12;

	/** A location theme by id ({@code village | bastion | end}; also {@code lobby | loan}); village when unknown. */
	public static CasinoTheme byId(String id) {
		for (CasinoTheme t : values()) if (t.id.equals(id)) return t;
		return VILLAGE;
	}

	/** Location theme of a level's dimension. */
	public static CasinoTheme of(Level level) {
		if (level == null) return VILLAGE;
		if (level.dimension() == Level.NETHER) return BASTION;
		if (level.dimension() == Level.END) return END;
		return VILLAGE;
	}

	/** Location theme where the local player is now. */
	public static CasinoTheme current() {
		Minecraft mc = Minecraft.getInstance();
		return of(mc == null ? null : mc.level);
	}

	public boolean location() {
		return this == VILLAGE || this == BASTION || this == END;
	}
}
