package dev.nezo.burmaldaholic.client.ui;

import dev.nezo.burmaldaholic.Burmaldaholic;
import dev.nezo.burmaldaholic.client.fx.FxSprites;
import net.minecraft.resources.Identifier;

/**
 * Sprite and sheet ids of the casino UI kit (generated by {@code tools/assets}: {@code core.mjs}, {@code core/menu.mjs},
 * {@code ui.mjs}). Atlas sprites ({@code textures/gui/sprites/core/…}) carry their nine-slice / tile / animation in
 * the {@code .mcmeta}; sheets ({@code textures/gui/core/…}) are UV-blitted by {@link CasinoUi#sheet}.
 */
public final class UiSprites {
	private UiSprites() {}

	/** {@code burmaldaholic:core/<path>}. */
	public static Identifier sprite(String path) {
		return FxSprites.sprite(path);
	}

	// ---- panels (global.md §2.2) --------------------------------------------------------------------------------------
	public static final Identifier PANEL_CASINO = sprite("panel/casino");
	public static final Identifier PANEL_INSET = sprite("panel/inset");
	public static final Identifier PANEL_FELT = sprite("panel/felt");
	public static final Identifier PANEL_HUD = sprite("panel/hud");
	public static final Identifier PANEL_HUD_GOLDEN = sprite("panel/hud_golden");

	/** A button sprite family: normal, highlighted (hover / focus), disabled; pressed = highlighted drawn 1 px lower. */
	public record Family(Identifier normal, Identifier highlighted, Identifier disabled) {
		public Identifier get(boolean active, boolean highlighted) {
			return !active ? disabled : highlighted ? this.highlighted : normal;
		}

		static Family of(String base) {
			return new Family(sprite(base), sprite(base + "_highlighted"), sprite(base + "_disabled"));
		}
	}

	public static final Family BUTTON_SECONDARY = Family.of("widget/casino_button");
	public static final Family BUTTON_PRIMARY = Family.of("widget/casino_button_primary");
	public static final Family BUTTON_DANGER = Family.of("widget/casino_button_danger");
	/** The big round casino-chip action button (ui.mjs, 40², pressed frame separate). */
	public static final Family BUTTON_ACTION = Family.of("ui/action_button");
	public static final Identifier BUTTON_ACTION_PRESSED = sprite("ui/action_button_pressed");
	/** Blank plates (ui.mjs): dark well with a gold rim (labels, amounts), 24 × 16, border 5. */
	public static final Identifier PLATE = sprite("ui/plate");
	public static final Identifier PLATE_GOLD = sprite("ui/plate_gold");

	// ---- the Casino Menu ledger shell (extras.md §8.1) ------------------------------------------------------------
	public static final Identifier SHELL = sprite("menu/shell");
	public static final Identifier SHELL_LOAN = sprite("menu/shell_loan");
	public static final Identifier PAGE = sprite("menu/page");
	public static final Identifier PAGE_LOAN = sprite("menu/page_loan");
	public static final Identifier TAB = sprite("menu/tab");
	public static final Identifier TAB_HOVER = sprite("menu/tab_hover");
	public static final Identifier TAB_SELECTED = sprite("menu/tab_selected");
	public static final Identifier TAB_LOAN = sprite("menu/tab_loan");
	public static final Identifier TAB_LOAN_SELECTED = sprite("menu/tab_loan_selected");
	public static final Identifier HEADER = sprite("menu/header");
	public static final Identifier BALANCE = sprite("menu/balance");
	public static final Identifier ROW = sprite("menu/row");
	public static final Identifier ROW_ALT = sprite("menu/row_alt");
	public static final Identifier ROW_HIGHLIGHT = sprite("menu/row_highlight");
	public static final Identifier ROW_LOAN = sprite("menu/row_loan");
	public static final Identifier PROGRESS = sprite("menu/progress");
	public static final Identifier ACH_LOCKED = sprite("menu/ach_plate_locked");
	public static final Identifier ACH_UNLOCKED = sprite("menu/ach_plate_unlocked");
	public static final Identifier ACH_GOLD = sprite("menu/ach_plate_gold");
	public static final Identifier DEBT_METER = sprite("menu/debt_meter");
	public static final Identifier DEBT_SKULL = sprite("menu/debt_skull");
	public static final Identifier STAMP = sprite("menu/stamp");
	public static final Identifier STAMP_OVERDUE = sprite("menu/stamp_overdue");
	public static final Identifier CONTRACT = sprite("menu/contract");
	public static final Identifier OFFER = sprite("menu/offer");
	public static final Identifier OFFER_LOCKED = sprite("menu/offer_locked");

	/** Progress bar fills (8 × 6 tiles). */
	public enum Fill {
		GOLD,
		GREEN,
		RED,
		LILAC;

		public final Identifier id = sprite("menu/progress_fill_" + name().toLowerCase(java.util.Locale.ROOT));
	}

	// ---- HUD and toasts (extras.md §9) -----------------------------------------------------------------------------
	public static final Identifier CHIP_COUNTER = sprite("hud/chip_counter");
	public static final Identifier CHIP_COUNTER_GOLDEN = sprite("hud/chip_counter_golden");
	/** 12² animated chip (4 frames, a shine every 16 t). */
	public static final Identifier CHIP_ICON = sprite("hud/chip_icon");
	public static final Identifier DELTA_UP = sprite("hud/delta_up");
	public static final Identifier DELTA_DOWN = sprite("hud/delta_down");

	public static Identifier flame(int frame) {
		return sprite("hud/flame_" + Math.floorMod(frame, 3));
	}

	public static Identifier cloud(int frame) {
		return sprite("hud/cloud_" + Math.floorMod(frame, 3));
	}

	public static Identifier badgeShine(int frame) {
		return sprite("hud/badge_shine_" + Math.floorMod(frame, 4));
	}

	public static final Identifier TOAST_CASINO = sprite("toast/casino");
	public static final Identifier TOAST_ACHIEVEMENT = sprite("toast/achievement");
	public static final Identifier TOAST_PVP = sprite("toast/pvp");
	public static final Identifier TOAST_LOAN = sprite("toast/loan");

	/** The cheeky speech bubble of the PvP kit (reused by the Loan Shark). */
	public static final Identifier BUBBLE_CHEEKY = Burmaldaholic.id("burmaldaholic/pvp/bubble_cheeky");

	// ---- sheets --------------------------------------------------------------------------------------------------
	/** A code-indexed sheet: a PNG under {@code textures/gui/…} of {@code w × h}. */
	public record Sheet(Identifier id, int w, int h) {}

	public static final Sheet TAB_ICONS_16 = new Sheet(Burmaldaholic.id("textures/gui/core/menu/tab_icons.png"), 176, 16);
	public static final Sheet TAB_ICONS_20 = new Sheet(Burmaldaholic.id("textures/gui/core/menu/tab_icons_20.png"), 220, 20);
	public static final Sheet TAB_ICONS_40 = new Sheet(Burmaldaholic.id("textures/gui/core/menu/tab_icons_40.png"), 440, 40);
	/** Achievement medals: locked, bronze, silver, gold (24² each). */
	public static final Sheet ACH_MEDALS = new Sheet(Burmaldaholic.id("textures/gui/core/menu/ach_medals.png"), 96, 24);
	/** The Loan Shark portrait (72²). */
	public static final Sheet SHARK = new Sheet(Burmaldaholic.id("textures/gui/core/menu/shark.png"), 72, 72);

	/** Menu / tab icons in the order of {@code tab_icons*.png} (extras.md §8.1). */
	public enum TabIcon {
		WALLET,
		VIP,
		CONTRACTS,
		LOAN,
		ACHIEVEMENTS,
		CHALLENGES,
		PVP,
		MY_CASINO,
		RULES,
		CASHIER,
		SETTINGS;

		/** Icon of a Casino Menu page id (server tabs included); {@code null} when the page has none. */
		public static TabIcon forPage(String page) {
			return switch (page == null ? "" : page) {
				case "wallet" -> WALLET;
				case "vip" -> VIP;
				case "contracts" -> CONTRACTS;
				case "loan" -> LOAN;
				case "achievements" -> ACHIEVEMENTS;
				case "challenges" -> CHALLENGES;
				case "bots", "pvp", "pvp_admin" -> PVP;
				case "my_casino" -> MY_CASINO;
				case "rules" -> RULES;
				case "cashier", "worldgen_shop" -> CASHIER;
				case "settings", "admin" -> SETTINGS;
				default -> null;
			};
		}
	}
}
