package dev.nezo.burmaldaholic.games.baccarat;

import dev.nezo.burmaldaholic.core.advancement.CasinoAdvancements;
import java.util.List;
import java.util.UUID;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;

/**
 * The four baccarat advancements of GAME_DESIGN §19 ({@code baccarat_natural}, {@code tie_streak},
 * {@code banco}, {@code bank_holder}). They are core ids ({@code data/burmaldaholic/advancement/core/<id>.json},
 * generated by {@code java/tools/gen_advancements.py}); this class only names them and delegates to
 * {@link CasinoAdvancements} (casino mode on, root first, offline players on their next join).
 */
public final class BaccaratAdvancements {
	public static final List<String> IDS = List.of("baccarat_natural", "tie_streak", "banco", "bank_holder");

	private BaccaratAdvancements() {}

	public static net.minecraft.resources.Identifier key(String id) {
		return CasinoAdvancements.key(id);
	}

	/** Offline-safe grant. */
	public static void grant(MinecraftServer server, UUID player, String id) {
		if (IDS.contains(id)) {
			CasinoAdvancements.grant(server, player, id);
		}
	}

	/** Grants to an online player; true if newly granted. */
	public static boolean grant(ServerPlayer player, String id) {
		return IDS.contains(id) && CasinoAdvancements.grant(player, id);
	}
}
