/**
 * Cross-edition fidelity vectors (docs/architecture/animation.md §3.4): recompute every output of
 * `test/fx/vectors/core_anim.json` (generated by the Java test `CoreAnimVectorsTest`) with the TypeScript
 * implementation. Also checks the glyph map has no overlaps.
 */
import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { EASE_IDS, ease, expDecay, outBack } from './ease';
import { glyphOverlaps } from './glyph-map';
import { rollUpDurationMs, rollUpValue } from './rollup';
import { FxRng, seedHash, seedMix } from './seed';
import { SOUND_DEFS } from './sound-ids';
import { LOCAL, Timeline, scaleMs } from './timeline';
import { DEFAULT_TIERS, SLOT_TIERS, type WinTier, winTierOf } from './win-tier';

interface Vectors {
  easeT: number[];
  ease: Record<string, number[]>;
  seedMix: Array<{ parts: number[]; out: number }>;
  hash: Array<{ s: string; out: number }>;
  fxRng: { seed: number; u32: number[]; int37: number[] };
  winTier: Array<{ ret: number; stake: number; table: 'DEFAULT' | 'SLOTS'; jackpot: boolean; floor?: WinTier; out: WinTier }>;
  rollUp: Array<{ ret: number; stake: number; min: number; max: number; dur: number; values: number[] }>;
  profileScale: Array<{ pct: number; ms: number; out: number }>;
  timeline: string;
  sounds: string[];
}

const file = path.resolve(__dirname, '../../../../test/fx/vectors/core_anim.json');
const v = JSON.parse(fs.readFileSync(file, 'utf8')) as Vectors;

/** The same sample timeline as Java `CoreAnimVectorsTest.sampleTimeline()`. */
export function sampleTimeline(): Timeline {
  const local = { speedPct: 150, reduceMotion: false, flashes: true };
  const b = Timeline.builder('demo', seedMix(7, 42));
  b.then(120, 'demo.spin_up', -1);
  for (let r = 0; r < 3; r++) b.add(600 + 150 * r - 350, 350, 'demo.reel_land', r, r * 11, 3);
  b.cue('demo.stop_sound', 2, 5);
  b.group(1)
    .clock(LOCAL)
    .then(scaleMs(local, 900), 'demo.win_show', -1, 1, 2, 3)
    .pause(scaleMs(local, 150))
    .then(scaleMs(local, rollUpDurationMs(40, 5, 600, 8000)), 'demo.rollup', -1, 40);
  return b.build();
}

describe('core_anim vectors (shared with Java)', () => {
  it('easing curves', () => {
    for (const id of EASE_IDS) v.easeT.forEach((t, i) => expect(ease(id, t)).toBeCloseTo(v.ease[id]![i]!, 12));
    v.easeT.forEach((t, i) => {
      expect(outBack(1.2, t)).toBeCloseTo(v.ease['outBack(1.2)']![i]!, 12);
      expect(expDecay(3.2, t)).toBeCloseTo(v.ease['expDecay(3.2)']![i]!, 12);
    });
  });
  it('seeds and cosmetic rng are bit-identical', () => {
    for (const c of v.seedMix) expect(seedMix(...c.parts)).toBe(c.out);
    for (const c of v.hash) expect(seedHash(c.s)).toBe(c.out);
    const r = new FxRng(v.fxRng.seed);
    expect(Array.from({ length: 8 }, () => r.nextU32())).toEqual(v.fxRng.u32);
    expect(Array.from({ length: 8 }, () => r.nextInt(37))).toEqual(v.fxRng.int37);
  });
  it('win tiers with per-game tables', () => {
    for (const c of v.winTier) expect(winTierOf(c.ret, c.stake, c.table === 'SLOTS' ? SLOT_TIERS : DEFAULT_TIERS, c.jackpot, c.floor)).toBe(c.out);
  });
  it('roll-ups and speed scaling', () => {
    for (const c of v.rollUp) {
      expect(rollUpDurationMs(c.ret, c.stake, c.min, c.max)).toBe(c.dur);
      expect([0, 0.1, 0.5, 0.9, 0.999, 1].map((t) => rollUpValue(c.ret, t))).toEqual(c.values);
    }
    for (const c of v.profileScale) expect(scaleMs({ speedPct: c.pct, reduceMotion: false, flashes: true }, c.ms)).toBe(c.out);
  });
  it('timeline canonical JSON is byte-identical', () => {
    expect(sampleTimeline().toCanonicalJson()).toBe(v.timeline);
    expect(sampleTimeline().sharedEndMs()).toBe(900);
  });
  it('sound catalog matches Java', () => {
    expect(SOUND_DEFS.map((s) => `${s.id}@${s.owner}`)).toEqual(v.sounds);
  });
  it('glyph map has no overlapping reservations', () => {
    expect(glyphOverlaps()).toEqual([]);
  });
});
