package dev.nezo.burmaldaholic.core.advancement;

import dev.nezo.burmaldaholic.Burmaldaholic;
import dev.nezo.burmaldaholic.core.CoreContent;
import dev.nezo.burmaldaholic.core.chips.ChipItem;
import dev.nezo.burmaldaholic.core.data.CasinoWorldData;
import dev.nezo.burmaldaholic.core.data.PlayerRecord;
import dev.nezo.burmaldaholic.core.events.CasinoEvents;
import dev.nezo.burmaldaholic.core.events.CasinoEvents.PlayResult;
import dev.nezo.burmaldaholic.core.mode.CasinoMode;
import dev.nezo.burmaldaholic.core.rng.StreakTracker;
import dev.nezo.burmaldaholic.core.wager.Stake;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents;
import net.minecraft.advancements.AdvancementHolder;
import net.minecraft.advancements.AdvancementProgress;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.item.ItemStack;

/**
 * Advancements of GAME_DESIGN.md §19 (tab "Burmaldaholic"). The advancements are data-driven
 * ({@code data/burmaldaholic/advancement/core/<id>.json}, generated by {@code java/tools/gen_advancements.py},
 * titles {@code advancement.burmaldaholic.<id>.title/.description}); each has one {@code minecraft:impossible}
 * criterion that {@link #grant} awards. Server thread only.
 *
 * <p>Core grants the core-observable ones itself: {@code root} (casino mode on + holds a chip or the
 * Casino Card), {@code first_bet}, {@code beginners_luck}, {@code heart_on_the_line}, {@code devils_deal},
 * {@code golden_hour} (from {@code PLAY_RESOLVED}) and {@code on_fire} / {@code black_cat} (streak ±10).
 * Modules call {@code CasinoAdvancements.grant(player, "hot_shooter")} for game-internal conditions.
 * Grants for offline players ({@link #grant(MinecraftServer, UUID, String)}) are queued and applied on join;
 * nothing is granted while casino mode is off.
 */
public final class CasinoAdvancements {
	/** Spec order (§19). */
	public static final List<String> IDS = List.of("root", "first_bet", "beginners_luck", "natural", "split_personality", "royal_flush",
		"shark_hunter", "top_five", "jackpot", "zero_hero", "hot_shooter", "plinko_edge", "scratch_top", "on_fire", "black_cat",
		"loan_taken", "knock_knock", "hostile_takeover", "clean_slate", "not_today", "scarred", "heart_on_the_line", "devils_deal",
		"golden_hour", "beam_me_up", "vip_silver", "vip_gold", "vip_platinum", "vip_diamond", "vip_netherite", "the_house",
		"house_always_wins", "bankrupt", "piglin_parlor", "high_roller",
		// 2026-09 games: granted by the baccarat / uth modules
		"baccarat_natural", "tie_streak", "uth_four_x", "banco", "bank_holder", "uth_house_seat", "uth_royal",
		// Seats & Bots (BOTS.md §10): granted by poker (man_vs_machine, clean_sweep) and chemin de fer (short_circuit)
		"man_vs_machine", "clean_sweep", "short_circuit",
		// slots v2 (SLOTS.md §14): granted by the slots module
		"mini_jackpot", "free_spins", "treasure_hunter", "tumble_six", "hoard_full", "void_walker", "dragon_core", "epic_win", "max_win");
	/** Retired id kept without a display so a holder's progress still loads (SLOTS.md §11: converted to top_five on join). */
	public static final String RETIRED_THREE_SEVENS = "three_sevens";
	private static final Set<String> KNOWN = Set.copyOf(IDS);
	/** Streak thresholds of on_fire / black_cat. */
	public static final int STREAK = 10;
	/** Owned-casino net profit for house_always_wins. */
	public static final long HOUSE_PROFIT = 10_000;

	private CasinoAdvancements() {}

	public static void register() {
		// registered after core's streak listener, so the streak already includes this round
		CasinoEvents.PLAY_RESOLVED.register(CasinoAdvancements::onPlay);
		ServerPlayConnectionEvents.JOIN.register((handler, sender, server) -> {
			ServerPlayer player = handler.getPlayer();
			deliver(player);
			checkRoot(player);
			if (has(player, RETIRED_THREE_SEVENS)) {
				grant(player, "top_five"); // SLOTS.md §11: the retired three_sevens becomes top_five
			}
		});
		ServerTickEvents.END_SERVER_TICK.register(server -> {
			if (server.getTickCount() % 100 == 0 && CasinoMode.isEnabled(server)) {
				server.getPlayerList().getPlayers().forEach(CasinoAdvancements::checkRoot);
			}
		});
	}

	/** Advancement id of a §19 id ({@code burmaldaholic:core/<id>}). */
	public static net.minecraft.resources.Identifier key(String id) {
		return Burmaldaholic.id("core/" + id);
	}

	/**
	 * Grants {@code id} to an online player (all criteria). Returns true if newly granted. Unknown ids and
	 * casino mode off: false. Grants {@code root} first so the tab is visible.
	 */
	public static boolean grant(ServerPlayer player, String id) {
		if (player == null || !KNOWN.contains(id) || player.hasDisconnected()) {
			return false;
		}
		MinecraftServer server = player.level().getServer();
		if (!CasinoMode.isEnabled(server)) {
			return false;
		}
		if (!id.equals("root")) {
			award(server, player, "root");
		}
		return award(server, player, id);
	}

	/** Offline-safe: grants now if the player is online, otherwise on their next join. */
	public static void grant(MinecraftServer server, UUID player, String id) {
		if (server == null || player == null || !KNOWN.contains(id)) {
			return;
		}
		ServerPlayer online = server.getPlayerList().getPlayer(player);
		if (online != null && !online.hasDisconnected()) {
			grant(online, id);
			return;
		}
		CasinoWorldData data = CasinoWorldData.get(server);
		PlayerRecord rec = data.player(player);
		if (!rec.pendingAdvancements.contains(id)) {
			rec.pendingAdvancements.add(id);
			data.setDirty();
		}
	}

	/** Whether the player already has {@code id}. */
	public static boolean has(ServerPlayer player, String id) {
		AdvancementHolder holder = player.level().getServer().getAdvancements().get(key(id));
		return holder != null && player.getAdvancements().getOrStartProgress(holder).isDone();
	}

	private static boolean award(MinecraftServer server, ServerPlayer player, String id) {
		AdvancementHolder holder = server.getAdvancements().get(key(id));
		if (holder == null) {
			return false;
		}
		AdvancementProgress progress = player.getAdvancements().getOrStartProgress(holder);
		if (progress.isDone()) {
			return false;
		}
		boolean any = false;
		for (String criterion : toList(progress.getRemainingCriteria())) {
			any |= player.getAdvancements().award(holder, criterion);
		}
		return any;
	}

	private static List<String> toList(Iterable<String> it) {
		List<String> out = new ArrayList<>();
		it.forEach(out::add);
		return out;
	}

	private static void deliver(ServerPlayer player) {
		MinecraftServer server = player.level().getServer();
		CasinoWorldData data = CasinoWorldData.get(server);
		PlayerRecord rec = data.player(player.getUUID());
		if (rec.pendingAdvancements.isEmpty() || !CasinoMode.isEnabled(server)) {
			return;
		}
		List<String> ids = List.copyOf(rec.pendingAdvancements);
		rec.pendingAdvancements.clear();
		data.setDirty();
		ids.forEach(id -> grant(player, id));
	}

	/** §19 root: casino mode on and the player holds any chip or a Casino Card. */
	static void checkRoot(ServerPlayer player) {
		if (!CasinoMode.isEnabled(player) || has(player, "root")) {
			return;
		}
		Inventory inv = player.getInventory();
		for (int i = 0; i < inv.getContainerSize(); i++) {
			ItemStack stack = inv.getItem(i);
			if (!stack.isEmpty() && (stack.is(CoreContent.CASINO_CARD) || ChipItem.valueOf(stack) > 0)) {
				grant(player, "root");
				return;
			}
		}
	}

	/** Core-observable wager / streak advancements. */
	static void onPlay(ServerPlayer player, PlayResult r) {
		for (String id : wagerAdvancements(r, StreakTracker.get(player.getUUID()))) {
			grant(player, id);
		}
	}

	/** Pure: the core-observable advancements one settled round unlocks (unit-tested). */
	public static List<String> wagerAdvancements(PlayResult r, int streakAfter) {
		List<String> out = new ArrayList<>();
		if (r.bet() < 1) {
			return out;
		}
		out.add("first_bet");
		if (r.net() > 0) {
			out.add("beginners_luck");
			if (r.stakeKind() == Stake.Kind.HEARTS) {
				out.add("heart_on_the_line");
			}
			if (r.stakeKind() == Stake.Kind.SOUL) {
				out.add("devils_deal");
			}
			if (r.goldenHour() && r.houseBanked()) {
				out.add("golden_hour");
			}
		}
		if (streakAfter >= STREAK) {
			out.add("on_fire");
		} else if (streakAfter <= -STREAK) {
			out.add("black_cat");
		}
		return out;
	}
}
