package dev.nezo.burmaldaholic.games.uth;

import dev.nezo.burmaldaholic.core.advancement.CasinoAdvancements;
import java.util.List;
import java.util.UUID;
import net.minecraft.resources.Identifier;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;

/**
 * The three §19 advancements of Ultimate Texas Hold'em ({@code uth_four_x}, {@code uth_royal},
 * {@code uth_house_seat}). They are core ids ({@code data/burmaldaholic/advancement/core/<id>.json}, generated by
 * {@code java/tools/gen_advancements.py}); grants go through {@link CasinoAdvancements} (casino mode on, root
 * first, offline players persisted and granted on their next join).
 */
public final class UthAdvancements {
	public static final String FOUR_X = "uth_four_x";
	public static final String ROYAL = "uth_royal";
	public static final String HOUSE_SEAT = "uth_house_seat";
	public static final List<String> IDS = List.of(FOUR_X, HOUSE_SEAT, ROYAL);

	private UthAdvancements() {}

	public static Identifier key(String id) {
		return CasinoAdvancements.key(id);
	}

	/** Offline-safe grant. */
	public static void grant(MinecraftServer server, UUID player, String id) {
		if (IDS.contains(id)) {
			CasinoAdvancements.grant(server, player, id);
		}
	}

	/** Grants to an online player; true if newly granted. */
	public static boolean grant(ServerPlayer player, String id) {
		return player != null && IDS.contains(id) && CasinoAdvancements.grant(player, id);
	}
}
